// Package client provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package client

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChargeStatus.
const (
	ChargeStatusFailed   ChargeStatus = "failed"
	ChargeStatusPending  ChargeStatus = "pending"
	ChargeStatusRefunded ChargeStatus = "refunded"
	ChargeStatusSettled  ChargeStatus = "settled"
)

// Valid indicates whether the value is a known member of the ChargeStatus enum.
func (e ChargeStatus) Valid() bool {
	switch e {
	case ChargeStatusFailed:
		return true
	case ChargeStatusPending:
		return true
	case ChargeStatusRefunded:
		return true
	case ChargeStatusSettled:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowHandleStatus.
const (
	WorkflowHandleStatusCancelled WorkflowHandleStatus = "cancelled"
	WorkflowHandleStatusCompleted WorkflowHandleStatus = "completed"
	WorkflowHandleStatusFailed    WorkflowHandleStatus = "failed"
	WorkflowHandleStatusRunning   WorkflowHandleStatus = "running"
)

// Valid indicates whether the value is a known member of the WorkflowHandleStatus enum.
func (e WorkflowHandleStatus) Valid() bool {
	switch e {
	case WorkflowHandleStatusCancelled:
		return true
	case WorkflowHandleStatusCompleted:
		return true
	case WorkflowHandleStatusFailed:
		return true
	case WorkflowHandleStatusRunning:
		return true
	default:
		return false
	}
}

// Charge defines model for Charge.
type Charge struct {
	AmountCents int                `json:"amount_cents"`
	Id          openapi_types.UUID `json:"id"`
	OrderId     openapi_types.UUID `json:"order_id"`
	Status      ChargeStatus       `json:"status"`
}

// ChargeStatus defines model for Charge.Status.
type ChargeStatus string

// ChargeInput defines model for ChargeInput.
type ChargeInput struct {
	AmountCents int                `json:"amount_cents"`
	OrderId     openapi_types.UUID `json:"order_id"`
}

// WorkflowHandle defines model for WorkflowHandle.
type WorkflowHandle struct {
	Id string `json:"id"`

	// ResultUrl GET to fetch terminal status + result
	ResultUrl *string              `json:"result_url,omitempty"`
	RunId     string               `json:"run_id"`
	Status    WorkflowHandleStatus `json:"status"`
}

// WorkflowHandleStatus defines model for WorkflowHandle.Status.
type WorkflowHandleStatus string

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// CreateChargeParams defines parameters for CreateCharge.
type CreateChargeParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// CreateChargeJSONRequestBody defines body for CreateCharge for application/json ContentType.
type CreateChargeJSONRequestBody = ChargeInput

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateChargeWithBody request with any body
	CreateChargeWithBody(ctx context.Context, params *CreateChargeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateCharge(ctx context.Context, params *CreateChargeParams, body CreateChargeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCharge request
	GetCharge(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateChargeWithBody(ctx context.Context, params *CreateChargeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateChargeRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateCharge(ctx context.Context, params *CreateChargeParams, body CreateChargeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateChargeRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCharge(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetChargeRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateChargeRequest calls the generic CreateCharge builder with application/json body
func NewCreateChargeRequest(server string, params *CreateChargeParams, body CreateChargeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateChargeRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateChargeRequestWithBody generates requests for CreateCharge with any type of body
func NewCreateChargeRequestWithBody(server string, params *CreateChargeParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/charges")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

	}

	return req, nil
}

// NewGetChargeRequest generates requests for GetCharge
func NewGetChargeRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/charges/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateChargeWithBodyWithResponse request with any body
	CreateChargeWithBodyWithResponse(ctx context.Context, params *CreateChargeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateChargeResponse, error)

	CreateChargeWithResponse(ctx context.Context, params *CreateChargeParams, body CreateChargeJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateChargeResponse, error)

	// GetChargeWithResponse request
	GetChargeWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetChargeResponse, error)
}

type CreateChargeResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON202                       *WorkflowHandle
	ApplicationproblemJSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r CreateChargeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateChargeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateChargeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetChargeResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *Charge
	ApplicationproblemJSONDefault *Error
}

// Status returns HTTPResponse.Status
func (r GetChargeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetChargeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetChargeResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// CreateChargeWithBodyWithResponse request with arbitrary body returning *CreateChargeResponse
func (c *ClientWithResponses) CreateChargeWithBodyWithResponse(ctx context.Context, params *CreateChargeParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateChargeResponse, error) {
	rsp, err := c.CreateChargeWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateChargeResponse(rsp)
}

func (c *ClientWithResponses) CreateChargeWithResponse(ctx context.Context, params *CreateChargeParams, body CreateChargeJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateChargeResponse, error) {
	rsp, err := c.CreateCharge(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateChargeResponse(rsp)
}

// GetChargeWithResponse request returning *GetChargeResponse
func (c *ClientWithResponses) GetChargeWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetChargeResponse, error) {
	rsp, err := c.GetCharge(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetChargeResponse(rsp)
}

// ParseCreateChargeResponse parses an HTTP response from a CreateChargeWithResponse call
func ParseCreateChargeResponse(rsp *http.Response) (*CreateChargeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateChargeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 202:
		var dest WorkflowHandle
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON202 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetChargeResponse parses an HTTP response from a GetChargeWithResponse call
func ParseGetChargeResponse(rsp *http.Response) (*GetChargeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetChargeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Charge
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}
