// Code generated by scripts/gen-openapi-public.sh; DO NOT EDIT.
// Scalar source list for the internal developer portal (ADR-0009, ADR-0014).
export const devportalSources = [
  { url: "/devportal/openapi/internal/catalog.json", title: "catalog", slug: "catalog" },
  { url: "/devportal/openapi/internal/orders.json", title: "orders", slug: "orders" },
  { url: "/devportal/openapi/internal/orgs.json", title: "orgs", slug: "orgs" },
  { url: "/devportal/openapi/internal/payment.json", title: "payment", slug: "payment" },
] as const;
