//go:build go1.22

// Package server provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package server

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ChargeStatus.
const (
	ChargeStatusFailed   ChargeStatus = "failed"
	ChargeStatusPending  ChargeStatus = "pending"
	ChargeStatusRefunded ChargeStatus = "refunded"
	ChargeStatusSettled  ChargeStatus = "settled"
)

// Valid indicates whether the value is a known member of the ChargeStatus enum.
func (e ChargeStatus) Valid() bool {
	switch e {
	case ChargeStatusFailed:
		return true
	case ChargeStatusPending:
		return true
	case ChargeStatusRefunded:
		return true
	case ChargeStatusSettled:
		return true
	default:
		return false
	}
}

// Defines values for WorkflowHandleStatus.
const (
	WorkflowHandleStatusCancelled WorkflowHandleStatus = "cancelled"
	WorkflowHandleStatusCompleted WorkflowHandleStatus = "completed"
	WorkflowHandleStatusFailed    WorkflowHandleStatus = "failed"
	WorkflowHandleStatusRunning   WorkflowHandleStatus = "running"
)

// Valid indicates whether the value is a known member of the WorkflowHandleStatus enum.
func (e WorkflowHandleStatus) Valid() bool {
	switch e {
	case WorkflowHandleStatusCancelled:
		return true
	case WorkflowHandleStatusCompleted:
		return true
	case WorkflowHandleStatusFailed:
		return true
	case WorkflowHandleStatusRunning:
		return true
	default:
		return false
	}
}

// Charge defines model for Charge.
type Charge struct {
	AmountCents int                `json:"amount_cents"`
	Id          openapi_types.UUID `json:"id"`
	OrderId     openapi_types.UUID `json:"order_id"`
	Status      ChargeStatus       `json:"status"`
}

// ChargeStatus defines model for Charge.Status.
type ChargeStatus string

// ChargeInput defines model for ChargeInput.
type ChargeInput struct {
	AmountCents int                `json:"amount_cents"`
	OrderId     openapi_types.UUID `json:"order_id"`
}

// WorkflowHandle defines model for WorkflowHandle.
type WorkflowHandle struct {
	Id string `json:"id"`

	// ResultUrl GET to fetch terminal status + result
	ResultUrl *string              `json:"result_url,omitempty"`
	RunId     string               `json:"run_id"`
	Status    WorkflowHandleStatus `json:"status"`
}

// WorkflowHandleStatus defines model for WorkflowHandle.Status.
type WorkflowHandleStatus string

// Error defines model for Error.
type Error struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

// CreateChargeParams defines parameters for CreateCharge.
type CreateChargeParams struct {
	IdempotencyKey string `json:"Idempotency-Key"`
}

// CreateChargeJSONRequestBody defines body for CreateCharge for application/json ContentType.
type CreateChargeJSONRequestBody = ChargeInput

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (POST /charges)
	CreateCharge(w http.ResponseWriter, r *http.Request, params CreateChargeParams)

	// (GET /charges/{id})
	GetCharge(w http.ResponseWriter, r *http.Request, id string)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// CreateCharge operation middleware
func (siw *ServerInterfaceWrapper) CreateCharge(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateChargeParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey string
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("Header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateCharge(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetCharge operation middleware
func (siw *ServerInterfaceWrapper) GetCharge(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", r.PathValue("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetCharge(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/charges", wrapper.CreateCharge)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/charges/{id}", wrapper.GetCharge)

	return m
}

type ErrorApplicationProblemPlusJSONResponse struct {
	Code    string                  `json:"code"`
	Details *map[string]interface{} `json:"details,omitempty"`
	Message string                  `json:"message"`
}

type CreateChargeRequestObject struct {
	Params CreateChargeParams
	Body   *CreateChargeJSONRequestBody
}

type CreateChargeResponseObject interface {
	VisitCreateChargeResponse(w http.ResponseWriter) error
}

type CreateCharge202JSONResponse WorkflowHandle

func (response CreateCharge202JSONResponse) VisitCreateChargeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type CreateChargedefaultApplicationProblemPlusJSONResponse struct {
	Body struct {
		Code    string                  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	}
	StatusCode int
}

func (response CreateChargedefaultApplicationProblemPlusJSONResponse) VisitCreateChargeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetChargeRequestObject struct {
	Id string `json:"id"`
}

type GetChargeResponseObject interface {
	VisitGetChargeResponse(w http.ResponseWriter) error
}

type GetCharge200JSONResponse Charge

func (response GetCharge200JSONResponse) VisitGetChargeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetChargedefaultApplicationProblemPlusJSONResponse struct {
	Body struct {
		Code    string                  `json:"code"`
		Details *map[string]interface{} `json:"details,omitempty"`
		Message string                  `json:"message"`
	}
	StatusCode int
}

func (response GetChargedefaultApplicationProblemPlusJSONResponse) VisitGetChargeResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/problem+json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (POST /charges)
	CreateCharge(ctx context.Context, request CreateChargeRequestObject) (CreateChargeResponseObject, error)

	// (GET /charges/{id})
	GetCharge(ctx context.Context, request GetChargeRequestObject) (GetChargeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// CreateCharge operation middleware
func (sh *strictHandler) CreateCharge(w http.ResponseWriter, r *http.Request, params CreateChargeParams) {
	var request CreateChargeRequestObject

	request.Params = params

	var body CreateChargeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateCharge(ctx, request.(CreateChargeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateCharge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateChargeResponseObject); ok {
		if err := validResponse.VisitCreateChargeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// GetCharge operation middleware
func (sh *strictHandler) GetCharge(w http.ResponseWriter, r *http.Request, id string) {
	var request GetChargeRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.GetCharge(ctx, request.(GetChargeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetCharge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(GetChargeResponseObject); ok {
		if err := validResponse.VisitGetChargeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}
