/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/internal/authorize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Ops-tier authorization decision for Oathkeeper's remote_json authorizer. */
        post: operations["authorize"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/operators": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Create an operator identity and grant the operator role. */
        post: operations["createOperator"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 7807 problem document. */
        Problem: {
            code: string;
            message: string;
            details?: {
                [key: string]: unknown;
            };
        };
        /** @description The remote_json payload Oathkeeper POSTs per ops-dashboard request. */
        AuthorizeRequest: {
            /** @description Kratos identity id; empty for anonymous. */
            subject: string;
            /** @description Ops dashboard slug such as o11y or network. */
            tool: string;
            /** @description authenticator_assurance_level from the session. */
            aal: string;
            /** @description The operator identity trait; "true" when set. */
            operator: string;
        };
        /** @description Request body to create an operator. */
        OperatorInput: {
            email: string;
            password: string;
        };
        /** @description A created operator. */
        Operator: {
            id: string;
            email: string;
        };
    };
    responses: {
        /** @description Error response */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    authorize: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The decision request forwarded by Oathkeeper. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorizeRequest"];
            };
        };
        responses: {
            /** @description Allowed. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Denied. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["Problem"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
    createOperator: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description The operator to create. */
        requestBody: {
            content: {
                "application/json": components["schemas"]["OperatorInput"];
            };
        };
        responses: {
            /** @description Created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Operator"];
                };
            };
            default: components["responses"]["Error"];
        };
    };
}
