// Code generated by ogen, DO NOT EDIT.

package authz

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// Authorize implements authorize operation.
//
// Ops-tier authorization decision for Oathkeeper's remote_json authorizer.
//
// POST /authorize
func (UnimplementedHandler) Authorize(ctx context.Context, req *AuthorizeRequest) (r AuthorizeRes, _ error) {
	return r, ht.ErrNotImplemented
}

// CreateOperator implements createOperator operation.
//
// Create an operator identity and grant the operator role.
//
// POST /operators
func (UnimplementedHandler) CreateOperator(ctx context.Context, req *OperatorInput) (r *Operator, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorStatusCode) {
	r = new(ErrorStatusCode)
	return r
}
