#!/usr/bin/env bash
# Emit the developer-portal spec projections the Scalar-rendered portals consume
# (ADR-0008, ADR-0009, ADR-0014). Two projections per the audience model:
#   - internal/  full specs, every operation (incl. x-internal). The internal
#                devportal (behind the /devportal session gate) renders these.
#   - public/    x-audience:public specs with x-internal operations stripped —
#                the anonymous public docs portal's data (ships with a public API).
# Named for its headline output (the public projection); the internal passthrough
# it emits alongside is what the always-on internal portal renders today.
# Outputs are generated artifacts: git-committed, Biome-ignored, drift-checked by
# ci:gen. YAML → JSON so the browser renderer needs no YAML parser.
set -euo pipefail

shopt -s nullglob

ROOT=$(cd "$(dirname "$0")/.." && pwd)
cd "$ROOT"

specs_dir="apps/frontend/public/devportal/openapi"
manifest="apps/frontend/src/devportal/specs.ts"

rm -rf "$specs_dir"
mkdir -p "$specs_dir/internal" "$specs_dir/public"

sources=""

for spec in services/*/openapi.yaml; do
  service=$(basename "$(dirname "$spec")")
  # _template is scaffolding, not a live service — never documented.
  [ "$service" = "_template" ] && continue

  echo "→ $service: internal projection"
  yq -o=json '.' "$spec" >"$specs_dir/internal/${service}.json"
  sources+="  { url: \"/devportal/openapi/internal/${service}.json\", title: \"${service}\", slug: \"${service}\" },"$'\n'

  audience=$(yq '.info.x-audience // "internal"' "$spec")
  if [ "$audience" = "public" ]; then
    echo "→ $service: public projection (x-internal stripped)"
    yq -o=json '
      del(.paths.*.* | select(tag == "!!map" and .x-internal == true))
      | del(.paths.* | select(tag == "!!map" and length == 0))
    ' "$spec" >"$specs_dir/public/${service}.json"
  fi
done

echo "→ devportal source manifest"
mkdir -p "$(dirname "$manifest")"
cat >"$manifest" <<EOF
// Code generated by scripts/gen-openapi-public.sh; DO NOT EDIT.
// Scalar source list for the internal developer portal (ADR-0009, ADR-0014).
export const devportalSources = [
${sources%$'\n'}
] as const;
EOF
